# Generated by Django 3.2.8 on 2021-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(default='sample@gmail.com', max_length=200, unique=True),
        ),
    ]
