# Generated by Django 3.2.8 on 2021-11-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0002_usermodels_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
