# Generated by Django 3.1 on 2021-11-28 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitapp', '0003_alter_usermodels_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
