# Generated by Django 3.1 on 2021-11-28 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitapp', '0004_auto_20211128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users_models', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
